fs:
  watch:
    - /tmp/watchme
    - ./tmp
  blacklist:
    - badfile.*
    - deleteme[0-9]+
    - dontletmelive
ps:
  watch:
    - sketchy
  blacklist:
    - malwareps
    - killthisproc
  prohibit:
    www-data:
      - /bin/sh
      - /bin/bash

extra:
  new:
    - other
    - stuff
